enum AppStorageKeys {
  static let isMoodTrackingEnabled = "isMoodTrackingEnabled"
  static let isRecapViewEnabled = "isRecapViewEnabled"
  static let isDeveloperModeEnabled = "isDeveloperModeEnabled"
  static let runtimeDebugEnabled = "runtimeDebugEnabled"
  static let cleanScreenshotsEnabled = "cleanScreenshotsEnabled"
  static let wandFillForce = "wandFillForce"
  static let appleHealthIntegrationEnabled = "appleHealthIntegrationEnabled"
  static let checkInSheetEnabled = "checkInSheetEnabled"
  static let milestoneCelebrationsEnabled = "milestoneCelebrationsEnabled"
  static let streakMilestoneCelebrationsEnabled = "streakMilestoneCelebrationsEnabled"
  static let showedUpMilestoneCelebrationsEnabled = "showedUpMilestoneCelebrationsEnabled"
  static let recapMilestoneCelebrationsEnabled = "recapMilestoneCelebrationsEnabled"
  static let onboardingSeenV1 = "onboarding.seen.v1"
  static let retentionLastRescheduleLocalDay = "notifications.retention.lastRescheduleLocalDay"
  static let cachedPremiumAccess = "premium.cachedAccess"
  static let dailyWallpaperTemplate = "dailyWallpaper.template"
  static let dailyWallpaperTheme = "dailyWallpaper.theme"
  static let dailyWallpaperAccentColor = "dailyWallpaper.accentColor"
  static let dailyWallpaperMessage = "dailyWallpaper.message"
}
